version = 0.1
[default.deploy.parameters]
stack_name = "talktodoc"
s3_bucket = "talktodoc"
s3_prefix = "talktodoc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
