AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  talktodoc

  Sample SAM Template for talktodoc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Parameters:
  Environment:
    Type: String

Resources:
  Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub talktodoc-${Environment}
      CodeUri: src/
      Handler: app.main.handler
      Runtime: python3.10
      MemorySize: 256
      Architectures:
      - x86_64
      Events:
        DefaultEndpoint:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  # Api:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     StageName: !Sub ${Environment}
  #     Cors:
  #       AllowMethods: "'*'"
  #       AllowHeaders: "'*'"
  #       AllowOrigin: "'*'"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
  Function:
    Description: talktodoc Lambda Function ARN
    Value: !GetAtt Function.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for talktodoc function
    Value: !GetAtt FunctionRole.Arn
