AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Sam Template

Globals:
  Function:
    Timeout: 30

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "talktodoc"
      MemorySize: 128
      CodeUri: src
      Handler: app.main.handler
      Runtime: python3.10
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods: 
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Accept
          - Access-Control-Allow-Headers
          - Access-Control-Request-Method
          - Access-Control-Request-Headers
          - Authorization

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'